### ISSUE TITLE
Fatal error ContentController.php on line 46 (migration from fluidcontent_bootstrap to fluidbootstraptheme)

### ISSUE THREAD

**Issue by Gruenbaer** [bootstraptheme-for-typo3/fluidbootstraptheme#239]
I have a site (TYPO3 6.2.6, PHP v. 5.4.34) which was running with fluidcontent_bootstrap.
All Extensions are up to date via repository.
As this extension is deprecated I uninstalled it and installed fluidbootstraptheme from repository instead (and fluidpages as required).
I then executed the update script in the extension manager which led to some updates.
I cleared the cache in the install tool, deleted the typo3temp content and recreated its folder structure, compared the database.

The frontend shows this error:
Fatal error: Call to a member function getOption() on a non-object in typo3/typo3conf/ext/fluidbootstraptheme/Classes/Controller/ContentController.php on line 46

I then git cloned the development versions of
EXT:flux (v.7.1.2)
EXT:vhs (v 2.14)
EXT:fluidcontent (v 4.1.1)
EXT:fluidpages (v 3.1.2)
EXT:fluidbootstraptheme(v 1.2.0)
and cleared/deleted the cache again.

The error message is still the same and I don't know what else I could do.

Best regards,

Emil

**Comment by Gruenbaer** [comment]
Nope, no such provider Extension.

**Comment by fabarea** [comment]
Is this issue still relevant? If yes, I would update its title since it concerns the migration from `fluidcontent_bootstrap` to `fluidbootstraptheme` as far as I can see.

**Comment by Gruenbaer** [comment]
Not relevan any more. I uninstalled it. Too buggy.
