### ISSUE TITLE
[TASK] Change nav-list to list-group

### ISSUE THREAD

**Issue by fschaeffer** [bootstraptheme-for-typo3/fluidbootstraptheme#240]
As of BS 3.0.1 the nav-list option was removed completely from BS and then later replaced by the list-group (https://github.com/twbs/bootstrap/issues/9139).

Now there are three options:
1.) provide the necessary CSS for the nav-list in fluidbottstraptheme (somebody posted a solution on SO http://stackoverflow.com/questions/18281636/what-replaces-nav-lists-in-bootstrap-3)
2.) provide a list-group template instead of the nav-list
3.) remove that option completely from fluidbootstraptheme.

As the list-group is an option but doesn't work exactly as the nav-list was working we could also go for 1+ 2 (as I often add the less for the nav-list back to BS3, the nav-list where really handy).

I would prepare the list-group template if there is any interest....

**Comment by mrvoss** [comment]
+1 for 2).

Note that the BS doc also has an [example for a heading inside a list group item](http://getbootstrap.com/components/#list-group-custom-content) - would be nice if this could be incorporated.

While you are at it - could you move the new "List group" CE from the 'Navigation' group / tab (where it is the only element) to the other CEs in the 'Bootstrap' group?

**Comment by misterboe** [comment]
@fschaeffer please create the list-group template and create a Pull Request into branch v2.0
