### ISSUE TITLE
Boostrap and Grid-option disappearing from new content wizard

### ISSUE THREAD

**Issue by fschaeffer** [bootstraptheme-for-typo3/fluidbootstraptheme#242]
Every once in a while the option for creating a bootstrap / grid element disappear from the new element wizard. If I then select "Hide content element" in fluidbootstraptheme-settings, clear cache, remove the tick again, clear cache the wizard offers me those additional tabs again. Some days later both tabs disappearing again I have to redo the whole setting-tick-untick-cache-thing again.

Any idea what cause this behaviour? Newest Flux/Fluid/Fluidbootstraptheme/TYPO3-core...

**Comment by fazzyx** [comment]
I have the exact same behavior. TYPO3 Version 6.2

**Comment by braguzz** [comment]
in my case sometimes disappare even the 'boostrap' CE folder. I have to clear cache from system install.

hu?

**Comment by fschaeffer** [comment]
Maybe some side effects of the recently discussed issue regarding load order for extbase extensions using Configuration/TCA, still experiencing the same issue every now and then

**Comment by misterboe** [comment]
have you checked it in dev branches of FT3 and fluidbootstraptheme branch v2.0

**Comment by fschaeffer** [comment]
The problem is that this error is not reproducable at all. Some weeks nothing happens, all editors are able to access the bootstrap panel as well as my custom build elements in an additional panel. Then without any further ado they disappear. Then I can only deactivate / activate the above mentioned checkboxes and they reappear.

Is there an upgrade path available for FT3 and fluidbootraptheme? Which versions of flux / vhs are necessary? This is one of the problems I have, these extension are heavily maintained and for every error in one of the extensions I have to upgrade a bunch of them.

Maybe it would be a good idea to publish a meta extension which takes care of a working set of versions for flux / fluidbootstraptheme / vhs / fluidpages / fluidcontent. It happened quite some times that updating ALL of them to dev versions broke some thing, which was working by upgrading only one of them to the dev version but leave the others on the stable / ter versions...

**Comment by braguzz** [comment]
no. I'm not checked but is a production server, and i'd like to not have some side effect...

the problem is that the error is hardly reproducible..
