### ISSUE TITLE
Activate / deactivate content elements

### ISSUE THREAD

**Issue by stefan1242** [bootstraptheme-for-typo3/fluidbootstraptheme#245]
Can I activate or deactivate the elements shown in backend (with typoscript) without changing the extension? For example i only want to see column row & tabs.

Thanks for help!

**Comment by randomresult** [comment]
Hi, for now you can only disable all Contentelements and use the page-templates only - or you can disable all page-templates and use Contentelements only. 

But you can try to overwrite this extension by your own provider and add the templates you dont want to show. In this templates you can set enabled="false" in the configruation section. 
To be honnest, i dont know if this enable/disable feature can be used with overwriting cause i think the overwrite-feature is only for main-Section (Frontend). 

At least you can ask @NamelessCoder if this is possible.

Another way would be to copy only the needed elements and copy it to your provider extension. 
Just some simple cleanups and your done. 
Cheers.

**Comment by NamelessCoder** [comment]
Hi guys,

We'll be implementing a feature in Flux 7.2 to let you override various settings of Flux forms, including enabled state, using TypoScript. The feature should become available in the Flux development branch some time during February.

Until that time you can use pageTSconfig to manually remove each of the element types you don't want - but that only works for content elements and only lets you remove the elements completely or change default values of a few key properties. The Flux 7.2 solution will also work for page templates.

**Comment by stefan1242** [comment]
thanks for your help :)!
