### ISSUE TITLE
Incompatibility with fluidcontent_core

### ISSUE THREAD

**Issue by potofcoffee** [bootstraptheme-for-typo3/fluidbootstraptheme#250]
I'm using fluidbootstraptheme (from TER) on a site with TYPO3 6.2.9 in combination with fluidcontent_core. All relevant extensions are the latest versions from TER--though I also tried using the latest versions from github, with the same results.

Page templates, etc. work fine. Fluid-based content objects from fluidcontent_core render fine, but the ones from fluidbootstraptheme are not rendered at all. If they have a heading, it is rendered, but the actual content object itself is not.

**Comment by apiening** [comment]
Exactly the same behaviour here.

I use TYPO3 version 6.2.10 in a fresh setup with the following versions for the "Fluid Theme for Twitter Bootstrap" (all from ter, came in as automatically resolved dependencies):
flux 7.1.2
vhs 2.2.0
fluidcontent 4.1.1
fluidpages 3.1.2

It doesn't matter what content element from the "Bootstrap" tab I choose: Only the Heading is filled with the title field. Everything else is rendered completely empty.

Any suggestens?

**Comment by potofcoffee** [comment]
I noticed that @PowerKiKi's commit b07bf1a2090211a0a8bcaa6c694bc771785a1d09 addresses this bug, but unfortunately not in the way of a fix.

Is there any indication of why this is happening? I'll gladly help dig, but, as for now, I have no clue where to start looking. 

I hope there will be a fix other than mentioning an incompatibility in the readme.

**Comment by PowerKiKi** [comment]
Sorry to hijack, but may I ask what for you are using fluidcontent_core ? When figuring out this incompatibility I could not understand what was the purpose of fluidcontent_core despite the README... ... so what is a croncrete use of it ?

**Comment by outdoorsman** [comment]
fluidcontent_core is a much cleaner (not as many inline styles, etc.) rendition of the default content elements in my opinion.  For instance in CSS Styled Content, when you insert a standard text content element it ALWAYS wraps a div around the content element... this is fine if you want that, but I've found that for mobile-first designs, that can be a real pain if you don't want it for some reason.  That's just the start. You can also modify how CE behave much more easily if you want to override default behavior... plus it's fluid driven :)

**Comment by potofcoffee** [comment]
That's about what I was going to say :)

**Comment by misterboe** [comment]
hey guys, please run the update script of fluidcontent_core in the ext manager

**Comment by potofcoffee** [comment]
It says there's nothing to update, which should not be surprising on a fresh install :-) Still doesn't help, though.

**Comment by potofcoffee** [comment]
What is not clear to me: Where exactly is fbt dependent on css_styled_content?

**Comment by PowerKiKi** [comment]
I was, and still am, puzzled too. I assumed that either fluidbootstraptheme or fluidcontent_core would completely eliminate the need for css_styled_content. But that's clearly not the case. The relationships and roles of theses three pieces are still fuzzy to me.

**Comment by misterboe** [comment]
@potofcoffee can u please test v.2.0 branch

**Comment by outdoorsman** [comment]
When in doubt, here's another possible fix that's helped me solve quirky issues when I first started using these suite of extensions...

It's possible to have permission problems causing some cache to not be able to be cleared properly.  You can double check this by setting proper ownership on your whole typo3conf/ext folder, rm -rf typo3temp/*, recreate missing typo3temp folders from the install tool, and then make certain to recursively set proper typo3temp permissions.

**Comment by randomresult** [comment]
The UpdateScript in FluidContent_core adds some lines to the AdditionalConfiguration. So its also needed on a fresh install. See install-instructions in fluidcontent_core. 
So pls. check if you have an AdditionalConfigruation.php with the needed lines for fcc.

**Comment by apiening** [comment]
Thank you very much randomresult, executing the update script resolved this issue. At least for me: My content gets rendered now after clearing the cache.

**Comment by coding46** [comment]
@PowerKiKi 
fcc is a replacement of csc.

fluidbootstraptheme was never meant to be an replacement of csc. It never will. In the first place it is an educational extension to show up all those nice things one can do with the ft3 extensions. It should work with and without [csc | fcc]. Depends on which extension you're using for standard content elements.

**Comment by PowerKiKi** [comment]
Thanks @coding46 and @Outdoorsman for the clarifications. Since I never knew what csc was doing, I always assumed it was useless :-P. But I think i now understand better the roles of each extensions

**Comment by misterboe** [comment]
i think this could be closed?

**Comment by potofcoffee** [comment]
Still no luck. As far as I can see, the update script sets a single line in AdditionalConfiguration.php:

```
$GLOBALS['TYPO3_CONF_VARS']['FE']['contentRenderingTemplates'] = array('fluidcontentcore/Configuration/TypoScript');
```

This line is present here. Cache has been cleared multiple times using all available means. typo3temp has been deleted and recreated completely. Still, everything is rendered _except_ fbt elements.

**Comment by apiening** [comment]
@potofcoffee Please can you check in your root template if the static template 'Fluid Styled Content (fluidcontent_core) are still included in your root template? I somehow broke this while messing with the extensions and needed it to add there again. After this I've choosen ''Clear all cache" in the Installer (it's under "Important actions").

**Comment by apiening** [comment]
I've updated the fluid extensions from the TER. The extension manager showed me an update icon and I couldn't resist.
Now my headings are not rendered anymore. The fluid based content is rendered completely, but whatever I put in the header field it is not displayed. This is true for all Fluid Content elements I've checked.
This is so strange, since this is quite the opposite of my initial problem where only my heading was rendered and no content.

**Comment by apiening** [comment]
I've downloaded a typo3 distribution 'speciality typo3' from ecodev, just to check if the headers are rendered there: They're not.
Just to make sure that I don't chase ghosts: Please can someone confirm if the header field get's displayed / rendered in the FE when he pics let's say a 'FLUID Content -  Image gallery' and puts some random text in the haeder-field?
Or the better: Should they? I mean for a 'responsable image' it may seem questionable if a header should be rendered at all, but for a image gallery for example I would expect it should.

**Comment by xf-** [comment]
Works fine together.
please update AddionalConfiguration. Should be 2 lines.

**Comment by potofcoffee** [comment]
@xf- There are still a number of unanswered reports (not only mine) above that state it doesn't work for everybody. I'm wondering how this closes the issue.

**Comment by xf-** [comment]
Last dev versions of FT3 works - you need to make sure the lines in AddionalConfiguration are present.
