### ISSUE TITLE
Wrong Fluid Content Type Listed

### ISSUE THREAD

**Issue by outdoorsman** [bootstraptheme-for-typo3/fluidbootstraptheme#263]
This is a screen shot of a Simple Responsive Image content element. All the correct fields are showing, but the Fluid Content type dropdown shows the wrong label as active. If I select Simple Responsive Image from the dropdown, **it selects the right fluid content type and associated fields but the label will always show one item further down in the list than the one that's currently selected**.

![fluidbootstraptheme-wrongfluidcontenttype](https://cloud.githubusercontent.com/assets/3075533/6719589/cbaadee2-cd78-11e4-9be5-f5aad196b21a.jpg)

**Comment by coding46** [comment]
It's a fluidcontent issue - see here https://github.com/FluidTYPO3/fluidcontent/issues/226

**Comment by outdoorsman** [comment]
Thanks. I didn't think fluidbootstraptheme was capable of doing that but noticed it when I moved to the v2.0 branch :)
