### ISSUE TITLE
Content not "mapped" to accordion item

### ISSUE THREAD

**Issue by Gruenbaer** [bootstraptheme-for-typo3/fluidbootstraptheme#269]
Hi,
I have created 4 accordion items (A, B, C, D) within the accordion Element, each with one "normal" content element (A1, B2, C3, D4).
Then I create a fifth accordion item (E) and drag and drop it to the first place.
So the order of the accordions is EABCD now.
Here's the issue: 
E now contains A1, A contains B2, and so on. D is empty.
Before --- After:
A -> A1   ---   E -> A1
B -> B2   ---   A -> B2
C -> C3   ---   B -> C3
D -> D4   ---   C -> D4
none       ---   D -> empty
If I delete Accordion E everything is back to normal.
So I assume that the content Elements are not "mapped" to its respective accordion, but merely to the position of the accordion item.

Best regards,

Emil

**Comment by boettner-it** [comment]
I just encountered the same issue as @Gruenbaer. I could take care of a fix but with a little hint it may be quicker to solve. Any chance anyone can assist for a minute for me to get an overview?

**Comment by misterboe** [comment]
please reopen as bug of version 2.0 if the problem is still there
