### ISSUE TITLE
Access flux/flexform to f.e. add wrapper-class for "Choose a Wrap Class"-Dropdown

### ISSUE THREAD

**Issue by typoworx-de** [bootstraptheme-for-typo3/fluidbootstraptheme#277]
Fluidbootstraptheme has some default grid-elements and an option tab for "Additional CSS" that has a dropdown labeled "Choose a Wrap Class". There are currently no styles.

Is it possible to add custom-styles by TypoScript for TS-Config / TCEFORM?

**Comment by misterboe** [comment]
yes, have a look in the constant editor, there are the default wraps
