### ISSUE TITLE
New TER release version 1.2.0

### ISSUE THREAD

**Issue by fabarea** [bootstraptheme-for-typo3/fluidbootstraptheme#278]
Is it possible to make a new TER release of version 1.2?

I am experimenting some icon problem on version 1.1 with TYPO3 6.2 which looks to be resolved with the upcoming 1.2. Thanks in advance.

![screenshot 2015-09-30 09 37 14](https://cloud.githubusercontent.com/assets/620730/10187672/4b289616-675a-11e5-91ae-5da739ed80f2.png)

**Comment by fabarea** [comment]
Here is the image path FYI. It is missing an additional "../"

![screenshot 2015-09-30 10 03 24](https://cloud.githubusercontent.com/assets/620730/10187709/8fa89cb4-675a-11e5-9540-64004d5468d4.png)

**Comment by PhilippRath** [comment]
me to and it is even stranger in typo 7.5 all requirements from TER

flux 7.2.3, fluidcontent 7.2.3, fluidpages 3.3.1, vhs 2.3.3, fluidbootstraptheme 1.2

![fluidbootstrapiconprob](https://cloud.githubusercontent.com/assets/8569417/10391726/2e83d8ee-6e81-11e5-8136-57f85b0741dc.png)

**Comment by PhilippRath** [comment]
it seems there is a bug in flux
https://github.com/FluidTYPO3/flux/issues/943

**Comment by fabarea** [comment]
Ping for a release of 1.2.0
