### ISSUE TITLE
Can't edit a element carousel in TYPO3 7.5

### ISSUE THREAD

**Issue by stwsimon** [bootstraptheme-for-typo3/fluidbootstraptheme#280]
Clicking the edit icon brings up the following:
#1: PHP Catchable Fatal Error: Argument 2 passed to FluidTYPO3\Flux\UserFunction\HtmlOutput::renderField() must be an instance of TYPO3\CMS\Backend\Form\FormEngine, instance of TYPO3\CMS\Backend\Form\Element\UserElement given in /home/seethrou/public_html/new7/typo3conf/ext/flux/Classes/UserFunction/HtmlOutput.php line 26

All extensions are up to date with the extension manager.

**Comment by misterboe** [comment]
please test the develop branch
