### ISSUE TITLE
Usage of fluidcontent_core still prohibited?

### ISSUE THREAD

**Issue by fschaeffer** [bootstraptheme-for-typo3/fluidbootstraptheme#282]
Hello,

I just setup a 7.5 installation, using the usual suspects (all newest version, even some using the git dev versions) including fluidbootstraptheme and fluidcontent_core and it works like a charme! So is it still true to NOT use fluidcontent_core alongside fluidbootstraptheme?

Or is there another easy way to have 
a.) base content like text rendered via fluid (fluidcontent_core)
b.) have all relevant bootstrap elements available as special element (fluidbootstraptheme)

I know there is the new fluid_styled_content but they are still messing up the HTML by using lots and lots of div so I'd rather use the (semantically clean) fluidcontent_core extension for rendering my default content elements...

Keep up the good work

**Comment by misterboe** [comment]
im Test at the moment on 6.2.15 and there seems no problem with FCC

have you used the extension manager to add these lines to you additional conf? 

```
<?php
$GLOBALS['TYPO3_CONF_VARS']['FE']['contentRenderingTemplates'] = array('fluidcontentcore/Configuration/TypoScript/');
$GLOBALS['TYPO3_CONF_VARS']['FE']['activateContentAdapter'] = 0;
```

**Comment by fschaeffer** [comment]
Hello,

I did nothing except installing them in EM :)

My Setup: Flux, VHS, Fluidcontent_core, fluidcontent, fluidpages, fluidbootstraptheme all in their TER-versions (including the current fluidbootstraptheme-bug for missing icons) on TYPO3 7.5 and an additional provider extension for my own pages / content elements. It's just working ....

**Comment by misterboe** [comment]
you have to press the update symbol in ext manager. This will add the needed code

**Comment by fschaeffer** [comment]
Actually it is working without any further ado. I was just asking whether the stated incompatibility between fluidbootstraptheme and fluidcontent_core is still valid (despite the fact that it IS working in my setup).
