### ISSUE TITLE
Add documentation how to add own elements

### ISSUE THREAD

**Issue by golserma** [bootstraptheme-for-typo3/fluidbootstraptheme#296]
I have created a copy of an existing element Well.html inside my extension.
If I try to use it I get [ INVALID VALUE ("FluidBT.Fluidbootstraptheme:Panel.html") ]

Do I have to register the name somehow or how does this work?

**Comment by xf-** [comment]
Your should use your own Provider extension.
Take a look at Builder from FluidTYPO3. Can generate a provider including a example and provides more documentation.
