### ISSUE TITLE
[FEATURE] German translation of content element titles etc.

### ISSUE THREAD

**Issue by apiening** [bootstraptheme-for-typo3/fluidbootstraptheme#297]
Hi there,
I wonder if there is a german translation of the content element titles and description. After running the typo3 translation module my content element are still labeled english, but my backend language is german.
If there is no translation yet, I would be glad to provide it for german.

**Comment by outdoorsman** [comment]
No there isn't a German translation... https://github.com/bootstraptheme-for-typo3/fluidbootstraptheme/blob/development/Resources/Private/Language/locallang.xlf

If you want to translate that would be great! Do a pull request when you're done and ping me.

**Comment by xf-** [comment]
i think this can be closed. PR is still welcome.
